# Generated by Django 4.2.6 on 2023-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngfwadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Устройство NGFW', 'verbose_name_plural': 'Устройства NGFW'},
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='device',
            name='login',
            field=models.CharField(max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(max_length=255, verbose_name='Порт'),
        ),
    ]
