# Generated by Django 4.2.6 on 2023-11-14 20:56

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngfwadmin', '0006_alter_device_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
